apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-mgmt-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/atolanrewaju2022/user-mgmt-app-helm-chart.git"
    targetRevision: HEAD
    path: kubernetes
  destination:
    namespace: default
    server: "https://kubernetes.default.svc" 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
     selfHeal: true
     prune: true
