image:
  repository: 060866400122.dkr.ecr.us-east-1.amazonaws.com/user-mgmt
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

resources: 
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
  # targetMemoryUtilizationPercentage: 80


application:
   name: user-mgmt
   labels: user-mgmt
   #environment: dev
   #selectorLabels: user-mgmt
   #serviceAccountName: user-mgmt-service-account

container:
   containerPort: 80
   portName: http
   protocol: TCP
   #livenessPort: http
   #readinessPort: http
  

service:
   name: http-manager
   type: NodePort
   port: 30001
   targetPort: 80
   protocol: TCP

namespace:
   name: default

rbac:
  clusterRole: user-mgmt-clusterrole

serviceAccount:
   name: user-mgmt-sa
   labels: user-mgmt-sa

nodeSelector: {}

tolerations: []

affinity: {}

