#  apiVersion: v1
#  kind: ServiceAccount
#  metadata:
#     name: account-manager-sa
#     labels: account-manager-sa
#     namespace: kube-system

# apiVersion: v1
# kind: ServiceAccount
# metadata:
#     name: account-manager-sa
#     namespace: dlframe
